# Note that it's important to define input and output before image definition
# input = "G:/Raw Data/Summer 2005/July 5, 2005"
# input = "G:/Raw Data/Summer 2005/July 13, 2005"
input = "G:/Raw Data/Summer 2005/July 14, 2005" 
# input = "G:/Raw Data/Summer 2005/July 31, 2005"
# input = "G:/Raw Data/Summer 2005/August 1, 2005"
# input = "G:/Raw Data/Summer 2005/August 4, 2005"
# input = "G:/Raw Data/Summer 2005/August 6, 2005"
# input = "G:/Raw Data/Summer 2005/August 7, 2005"
# input = "G:/Raw Data/Summer 2005/August 8, 2005"
# input = "G:/Raw Data/Summer 2005/August 20, 2005"
# input = "G:/Raw Data/Summer 2005/August 21, 2005"
# input = "G:/Raw Data/Summer 2005/August 27, 2005"
# input = "G:/Raw Data/Summer 2005/August 30, 2005"

output = "E:/Data Processing/Master Flats/2005"


[image]
rows = 1024
columns = 1024

