[image]
rows = 1024
columns = 1024


[processing]
no_of_images_to_combine = 28
image_duration = 2.5
radii_of_extraction = [3, 4, 5,]
cpu_fraction = 0.4


[input]

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/June 23, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-06-26_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/June 26, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-06-26_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/June 30, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-06-26_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/July 4, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-07-04_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/July 7, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-07-07_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/July 9, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-07-09_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/July 10, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-07-10_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/July 13, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-07-13_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/July 14, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-07-14_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/July 16, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-07-14_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/July 21, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-07-22_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/July 22, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-07-22_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/July 27, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-07-27_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/July 28, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-07-27_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/July 31, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-07-31_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/August 1, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-08-01_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/August 4, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-08-04_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/August 6, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-08-06_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/August 7, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-08-07_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/August 8, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-08-08_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/August 20, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-08-20_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/August 21, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-08-21_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/August 27, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-08-27_masterflat_2.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2005/August 30, 2005"
    masterflat = "E:/Data Processing/Master Flats/2005/2005-08-30_masterflat_2.5.fit"
    



[output]
path = "E:/Data Processing/Python Processed/2005"