[image]
rows = 1024
columns = 1024


[processing]
no_of_images_to_combine = 10
radii_of_extraction = [3, 4, 5,]

[input]

# Using 2-22 flat: 2-14 -> 2-22
    [[input.nights]]
    path = "H://Raw Data/Summer 2014/February 17, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-02-22_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/February 18, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-02-22_masterflat.fit"

    # [[input.nights]]
    # path = "H://Raw Data/Summer 2014/February 21, 2014" # No darks in this night
    # masterflat = "E:/Data Processing/Master Flats/2014/2014-02-22_masterflat.fit"  

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/February 22, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-02-22_masterflat.fit"

# # Using 3-25 flat: 3-20 -> 3-25
    [[input.nights]]
    path = "H://Raw Data/Summer 2014/March 20, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-03-25_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/March 25, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-03-25_masterflat.fit"

# # Using 3-29 flat: 3-29 
    [[input.nights]]
    path = "H://Raw Data/Summer 2014/March 29, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-03-29_masterflat.fit"

# # Using 4-1 flat: 4-1 -> 4-8
    [[input.nights]]
    path = "H://Raw Data/Summer 2014/April 1, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-04-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/April 4, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-04-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/April 8, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-04-01_masterflat.fit"
    
# # Using 4-25 flat: 4-21 -> 5-29: 
    [[input.nights]]
    path = "H://Raw Data/Summer 2014/April 21, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-04-25_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/April 25, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-04-25_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/May 2, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-04-25_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/May 5, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-04-25_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/May 9, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-04-25_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/May 13, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-04-25_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/May 21, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-04-25_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/May 22, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-04-25_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/May 23, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-04-25_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/May 24, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-04-25_masterflat.fit"
    
    [[input.nights]]
    path = "H://Raw Data/Summer 2014/May 28, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-04-25_masterflat.fit"
    
    [[input.nights]]
    path = "H://Raw Data/Summer 2014/May 29, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-04-25_masterflat.fit"

# # Using 6-15 flat: 6-15 -> 7-6
    [[input.nights]]
    path = "H://Raw Data/Summer 2014/June 15, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-06-15_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/June 25, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-06-15_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/July 2, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-06-15_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/July 3, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-06-15_masterflat.fit"
    
    [[input.nights]]
    path = "H://Raw Data/Summer 2014/July 6, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-06-15_masterflat.fit"
    
    [[input.nights]]
    path = "H://Raw Data/Summer 2014/July 8, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-06-15_masterflat.fit"

# # Using 7-22 flat: 7-15 -> 7-31
    [[input.nights]]
    path = "H://Raw Data/Summer 2014/July 15, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-07-22_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/July 16, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-07-22_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/July 17, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-07-22_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/July 22, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-07-22_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/July 23, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-07-22_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/July 27, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-07-22_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/July 31, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-07-22_masterflat.fit"

# # Using 8-12 flat: 8-11 -> 8-12
    [[input.nights]]
    path = "H://Raw Data/Summer 2014/August 11, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-08-12_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/August 12, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-08-12_masterflat.fit"

# # Using 9-2 flat: 9-2 -> 9-7
    [[input.nights]]
    path = "H://Raw Data/Summer 2014/September 2, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-09-02_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/September 6, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-09-02_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/September 7, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-09-02_masterflat.fit"

# # Using 9-13 flat: 9-13 -> 
    [[input.nights]]
    path = "H://Raw Data/Summer 2014/September 13, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-09-13_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/September 15, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-09-13_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/September 16, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-09-13_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/September 17, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-09-13_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/September 21, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-09-13_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/September 22, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-09-13_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/September 26, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-09-13_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2014/September 28, 2014"
    masterflat = "E:/Data Processing/Master Flats/2014/2014-09-13_masterflat.fit"

[output]
path = "E:/Data Processing/Python Processed/2014"