[image]
rows = 1024
columns = 1024


[processing]
no_of_images_to_combine = 10
radii_of_extraction = [3, 4, 5,]



[input]

    [[input.nights]]
    path = "H:/Raw Data/Summer 2018/June 3, 2018"
    masterflat = "E:/Data Processing/Master Flats/2018/2018-07-01_masterflat.fit"

    [[input.nights]]
    path = "H:/Raw Data/Summer 2018/July 1, 2018"
    masterflat = "E:/Data Processing/Master Flats/2018/2018-07-01_masterflat.fit"

    [[input.nights]]
    path = "H:/Raw Data/Summer 2018/July 2, 2018"
    masterflat = "E:/Data Processing/Master Flats/2018/2018-07-01_masterflat.fit"

    [[input.nights]]
    path = "H:/Raw Data/Summer 2018/July 3, 2018"
    masterflat = "E:/Data Processing/Master Flats/2018/2018-07-01_masterflat.fit"

    [[input.nights]]
    path = "H:/Raw Data/Summer 2018/July 5, 2018"
    masterflat = "E:/Data Processing/Master Flats/2018/2018-07-01_masterflat.fit"

    [[input.nights]]
    path = "H:/Raw Data/Summer 2018/July 6, 2018"
    masterflat = "E:/Data Processing/Master Flats/2018/2018-07-01_masterflat.fit"

    [[input.nights]]
    path = "H:/Raw Data/Summer 2018/July 7, 2018"
    masterflat = "E:/Data Processing/Master Flats/2018/2018-07-01_masterflat.fit"

    [[input.nights]]
    path = "H:/Raw Data/Summer 2018/July 8, 2018"
    masterflat = "E:/Data Processing/Master Flats/2018/2018-07-01_masterflat.fit"

    [[input.nights]]
    path = "H:/Raw Data/Summer 2018/July 10, 2018"
    masterflat = "E:/Data Processing/Master Flats/2018/2018-07-01_masterflat.fit"

    [[input.nights]]
    path = "H:/Raw Data/Summer 2018/July 16, 2018"
    masterflat = "E:/Data Processing/Master Flats/2018/2018-07-01_masterflat.fit"


[output]
path = "E:/Data Processing/Python Processed/2018"
