[processing]
radii_of_extraction = [3, 4, 5,]


# [reference]
# file = "E:/Data Processing/Reference Files/ref_revised_71.txt"
# logfile = "E:/Data Processing/Reference Files/08-05-03_m23_3.5-071.txt"
# color = "E:/Data Processing/Reference Files/MeanRI100.txt"

[input]

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2018/June 03, 2018"
    # first_logfile_number = 16
    # last_logfile_number = 1000

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2018/July 01, 2018"
    # first_logfile_number = 1
    # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2018/July 02, 2018"
    # first_logfile_number = 1
    # last_logfile_number = 88
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2018/July 03, 2018"
    # first_logfile_number = 18
    # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2018/July 05, 2018"
    # first_logfile_number = 12
    # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2018/July 06, 2018"
    # first_logfile_number = 1
    # last_logfile_number = 110
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2018/July 07, 2018"
    # first_logfile_number = 13
    # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2018/July 08, 2018"
    # first_logfile_number = 1
    # last_logfile_number = 114
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2018/July 10, 2018"
    # first_logfile_number = 18
    # last_logfile_number = 79
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2018/July 16, 2018"
    # first_logfile_number = 42
    # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2018/July 17, 2018"
    # first_logfile_number = 22
    # last_logfile_number = 63
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2018/July 31, 2018"
    # first_logfile_number = 45
    # last_logfile_number = 1000


    