# Note that it's important to define input and output before image definition
input = "F:/Summer 2019/July 29, 2019"
output = "E:/Data Processing/Master Flats/2019"


[image]
rows = 1024
columns = 1024

