[processing]
radii_of_extraction = [3, 4, 5,]


[reference]
file = "E:/Data Processing/Reference Files/ref_revised_71.txt"
logfile = "E:/Data Processing/Reference Files/08-05-03_m23_3.5-071.txt"
color = "E:/Data Processing/Reference Files/MeanRI100.txt"


[input]
   
    # [[input.nights]]
    # path = "E:/Data Processing/Python Processed/2015/March 01, 2015"
    # first_logfile_number = 1
    # last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/March 05, 2015"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/March 08, 2015"
    first_logfile_number = 18
    last_logfile_number = 30
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/March 09, 2015"
    first_logfile_number = 16
    last_logfile_number = 40
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/March 14, 2015"
    first_logfile_number = 22
    last_logfile_number = 35
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/March 25, 2015"
    first_logfile_number = 30
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/March 31, 2015"
    first_logfile_number = 18
    last_logfile_number = 45
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/April 05, 2015"
    first_logfile_number = 50
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/April 11, 2015"
    first_logfile_number = 35
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/April 13, 2015"
    first_logfile_number = 15
    last_logfile_number = 67
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/April 22, 2015"
    first_logfile_number = 24
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/April 25, 2015"
    first_logfile_number = 45
    last_logfile_number = 80
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/April 26, 2015"
    first_logfile_number = 42
    last_logfile_number = 90
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/April 30, 2015"
    first_logfile_number = 57
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/May 12, 2015"
    first_logfile_number = 30
    last_logfile_number = 52
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/May 20, 2015"
    first_logfile_number = 11
    last_logfile_number = 62
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/May 21, 2015"
    first_logfile_number = 19
    last_logfile_number = 80
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/May 27, 2015"
    first_logfile_number = 28
    last_logfile_number = 106
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/June 01, 2015"
    first_logfile_number = 40
    last_logfile_number = 110
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/June 08, 2015"
    first_logfile_number = 117
    last_logfile_number = 150
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/June 15, 2015"
    first_logfile_number = 45
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/June 18, 2015"
    first_logfile_number = 41
    last_logfile_number = 156
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/June 22, 2015"
    first_logfile_number = 20
    last_logfile_number = 100
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/June 23, 2015"
    first_logfile_number = 90
    last_logfile_number = 160
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/July 03, 2015"
    first_logfile_number = 80
    last_logfile_number = 120
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/July 09, 2015"
    first_logfile_number = 70
    last_logfile_number = 110
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/July 14, 2015"
    first_logfile_number = 76
    last_logfile_number = 115
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/July 19, 2015"
    first_logfile_number = 1
    last_logfile_number = 63
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/July 20, 2015"
    first_logfile_number = 53
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/July 21, 2015"
    first_logfile_number = 58
    last_logfile_number = 100
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/July 23, 2015"
    first_logfile_number = 1
    last_logfile_number = 50
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/August 03, 2015"
    first_logfile_number =67 
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/August 10, 2015"
    first_logfile_number = 40
    last_logfile_number = 84
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/August 11, 2015"
    first_logfile_number = 42
    last_logfile_number = 70
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/August 14, 2015"
    first_logfile_number = 7
    last_logfile_number = 46
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/August 15, 2015"
    first_logfile_number = 1
    last_logfile_number = 30
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/August 20, 2015"
    first_logfile_number = 10
    last_logfile_number = 30
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/August 21, 2015"
    first_logfile_number = 1
    last_logfile_number = 36
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/September 12, 2015"
    first_logfile_number = 30
    last_logfile_number = 45
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/September 13, 2015"
    first_logfile_number = 8
    last_logfile_number = 35
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/September 26, 2015"
    first_logfile_number = 5
    last_logfile_number = 11
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/September 27, 2015"
    first_logfile_number = 16
    last_logfile_number = 25
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/September 29, 2015"
    first_logfile_number = 18
    last_logfile_number = 25
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/September 30, 2015"
    first_logfile_number = 20
    last_logfile_number = 32
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/October 01, 2015"
    first_logfile_number = 10
    last_logfile_number = 19
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/October 02, 2015"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/October 11, 2015"
    first_logfile_number = 3
    last_logfile_number = 8
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/October 14, 2015"
    first_logfile_number = 1
    last_logfile_number = 7
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2015/October 15, 2015"
    first_logfile_number = 2
    last_logfile_number = 9
    
 
 