[image]
rows = 1024
columns = 1024


[processing]
no_of_images_to_combine = 20
radii_of_extraction = [3, 4, 5,]



[input]

# Using ... flat: .. -> ..
    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/February 24, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/February 27, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/March 2, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/March 3, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/March 4, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/March 5, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/March 14, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/March 17, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/March 20, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/March 21, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/March 22, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/March 25, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/April 7, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/April 8, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/April 16, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/April 17, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/April 20, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/April 21, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/April 27, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/May 5, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/May 8, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/May 13, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/May 18, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/May 24, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/May 26, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/May 27, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/June 15, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/June 16, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/June 23, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/June 27, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/June 28, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/June 29, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/June 30, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/July 1, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/July 2, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/July 9, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/July 13, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/July 15, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/July 18, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/July 19, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/July 20, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    [[input.nights]]
    path = "H:/Raw Data/Summer 2010/July 25, 2010"
    masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/July 26, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    [[input.nights]]
    path = "H:/Raw Data/Summer 2010/July 28, 2010"
    masterflat = "E:/Data Processing/Master Flats/2010/2010-02-27_masterflat.fit"
    

    ### Using 7-31 flat:

    [[input.nights]]
    path = "H:/Raw Data/Summer 2010/July 31, 2010"
    masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/August 1, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/August 4, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/August 5, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/August 7, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/August 11, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/August 12, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/August 16, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/August 21, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    # Does not have darks in the Calibration Frames folder
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/August 22, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/August 23, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/August 24, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/August 25, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/August 26, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/August 27, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/August 28, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/September 1, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/September 4, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/September 7, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/September 11, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/September 12, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/September 20, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/September 26, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/September 29, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/September 30, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/October 2, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/October 3, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit" 
    # no raw images in m23 folder 

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/October 4, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/October 5, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/October 6, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/October 7, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    

    # [[input.nights]]
    # path = "H:/Raw Data/Summer 2010/October 8, 2010"
    # masterflat = "E:/Data Processing/Master Flats/2010/2010-07-31_masterflat.fit"
    


[output]
path = "E:/Data Processing/Python Processed/2010"