[processing]
radii_of_extraction = [3, 4, 5,]


# [reference]
# file = "E:/Data Processing/Reference Files/ref_revised_71.txt"
# logfile = "E:/Data Processing/Reference Files/08-05-03_m23_3.5-071.txt"
# color = "E:/Data Processing/Reference Files/MeanRI100.txt"


[input]

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/February 24, 2010"
    first_logfile_number = 6
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/February 27, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 02, 2010"
    first_logfile_number = 12
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 03, 2010"
    first_logfile_number = 3
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 04, 2010"
    first_logfile_number = 9
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 05, 2010"
    first_logfile_number = 1
    last_logfile_number = 14
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 14, 2010"
    first_logfile_number = 5
    last_logfile_number = 29
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 17, 2010"
    first_logfile_number = 1
    last_logfile_number = 14
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 20, 2010"
    first_logfile_number = 13
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 21, 2010"
    first_logfile_number = 14
    last_logfile_number = 33
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 22, 2010"
    first_logfile_number = 13
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 25, 2010"
    first_logfile_number = 24
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/April 07, 2010"
    first_logfile_number = 19
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/April 08, 2010"
    first_logfile_number = 11
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/April 16, 2010"
    first_logfile_number = 10
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/April 17, 2010"
    first_logfile_number = 8
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/April 20, 2010"
    first_logfile_number = 17
    last_logfile_number = 51
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/April 21, 2010"
    first_logfile_number = 28 
    last_logfile_number = 61
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/April 27, 2010"
    first_logfile_number = 12
    last_logfile_number = 47
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/May 05, 2010"
    first_logfile_number = 31
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/May 08, 2010"
    first_logfile_number = 54
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/May 13, 2010"
    first_logfile_number = 40
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/May 18, 2010"
    first_logfile_number = 46
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/May 24, 2010"
    first_logfile_number = 16
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/May 26, 2010"
    first_logfile_number = 36
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/May 27, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/June 15, 2010"
    first_logfile_number = 54
    last_logfile_number = 103
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/June 16, 2010"
    first_logfile_number = 15
    last_logfile_number = 63
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/June 23, 2010"
    first_logfile_number = 53
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/June 27, 2010"
    first_logfile_number = 76
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/June 28, 2010"
    first_logfile_number = 1
    last_logfile_number = 80
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/June 29, 2010"
    first_logfile_number = 7
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/June 30, 2010"
    first_logfile_number = 1 
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 01, 2010"
    first_logfile_number = 9
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 02, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 09, 2010"
    first_logfile_number = 1
    last_logfile_number = 79
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 13, 2010"
    first_logfile_number = 1
    last_logfile_number = 34
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 15, 2010"
    first_logfile_number = 1
    last_logfile_number = 41
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 18, 2010"
    first_logfile_number = 1
    last_logfile_number = 25
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 19, 2010"
    first_logfile_number = 1
    last_logfile_number = 61
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 20, 2010"
    first_logfile_number = 22
    last_logfile_number = 70
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 25, 2010"
    first_logfile_number = 2 
    last_logfile_number = 23
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 26, 2010"
    first_logfile_number = 1
    last_logfile_number = 56
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 28, 2010"
    first_logfile_number = 41
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 31, 2010"
    first_logfile_number = 1
    last_logfile_number = 32
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 01, 2010"
    first_logfile_number = 1
    last_logfile_number = 43
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 04, 2010"
    first_logfile_number = 6
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 05, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 07, 2010"
    first_logfile_number = 1
    last_logfile_number = 59
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 11, 2010"
    first_logfile_number = 8
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 12, 2010"
    first_logfile_number = 2
    last_logfile_number = 48


    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 16, 2010"
    first_logfile_number = 1
    last_logfile_number = 17
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 22, 2010"
    first_logfile_number = 1
    last_logfile_number = 43
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 23, 2010"
    first_logfile_number = 1
    last_logfile_number = 34
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 24, 2010"
    first_logfile_number = 1
    last_logfile_number = 36
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 25, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 26, 2010"
    first_logfile_number = 5
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 27, 2010"
    first_logfile_number = 4
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 28, 2010"
    first_logfile_number = 1
    last_logfile_number = 41
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 01, 2010"
    first_logfile_number = 1
    last_logfile_number = 33
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 04, 2010"
    first_logfile_number = 4
    last_logfile_number = 33
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 07, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 11, 2010"
    first_logfile_number = 1 
    last_logfile_number = 23
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 12, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 20, 2010"
    first_logfile_number = 1
    last_logfile_number = 27
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 26, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 29, 2010"
    first_logfile_number = 4
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 30, 2010"
    first_logfile_number = 1
    last_logfile_number = 19
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/October 02, 2010"
    first_logfile_number = 6
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/October 04, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/October 05, 2010"
    first_logfile_number = 1
    last_logfile_number = 18
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/October 06, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000

    
    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/October 07, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000


    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/October 08, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000
    
