[processing]
radii_of_extraction = [3, 4, 5,]


[reference]
file = "E:/Data Processing/Reference Files/ref_revised_71.txt"
logfile = "E:/Data Processing/Reference Files/08-05-03_m23_3.5-071.txt"
color = "E:/Data Processing/Reference Files/MeanRI100.txt"


[input]

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/February 24, 2010"
    first_logfile_number = 13
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/February 27, 2010"
    first_logfile_number = 1
    last_logfile_number = 18
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 02, 2010"
    first_logfile_number = 26
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 03, 2010"
    first_logfile_number = 28
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 04, 2010"
    first_logfile_number = 28
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 05, 2010"
    first_logfile_number = 1
    last_logfile_number = 28
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 14, 2010"
    first_logfile_number = 30
    last_logfile_number = 54
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 17, 2010"
    first_logfile_number = 1
    last_logfile_number = 27
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 20, 2010"
    first_logfile_number = 28
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 21, 2010"
    first_logfile_number = 68
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 22, 2010"
    first_logfile_number = 40
    last_logfile_number = 80
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/March 25, 2010"
    first_logfile_number = 60
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/April 07, 2010"
    first_logfile_number = 38
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/April 08, 2010"
    first_logfile_number = 20
    last_logfile_number = 78
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/April 16, 2010"
    first_logfile_number = 25
    last_logfile_number = 79
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/April 17, 2010"
    first_logfile_number = 78
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/April 20, 2010"
    first_logfile_number = 30
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/April 21, 2010"
    first_logfile_number =50 
    last_logfile_number = 72
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/April 27, 2010"
    first_logfile_number = 41
    last_logfile_number = 90
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/May 05, 2010"
    first_logfile_number = 80
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/May 08, 2010"
    first_logfile_number = 108
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/May 13, 2010"
    first_logfile_number = 77
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/May 18, 2010"
    first_logfile_number = 80
    last_logfile_number = 175
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/May 24, 2010"
    first_logfile_number = 1
    last_logfile_number = 60
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/May 26, 2010"
    first_logfile_number = 80
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/May 27, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/June 15, 2010"
    first_logfile_number = 100
    last_logfile_number = 200
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/June 16, 2010"
    first_logfile_number = 40
    last_logfile_number = 80
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/June 23, 2010"
    first_logfile_number = 115
    last_logfile_number = 180
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/June 27, 2010"
    first_logfile_number = 146
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/June 28, 2010"
    first_logfile_number = 1
    last_logfile_number = 110
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/June 29, 2010"
    first_logfile_number = 23
    last_logfile_number = 57
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/June 30, 2010"
    first_logfile_number =165 
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 01, 2010"
    first_logfile_number = 28
    last_logfile_number = 74
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 02, 2010"
    first_logfile_number = 25
    last_logfile_number = 75
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 09, 2010"
    first_logfile_number = 125
    last_logfile_number = 156
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 13, 2010"
    first_logfile_number = 1
    last_logfile_number = 42
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 15, 2010"
    first_logfile_number = 1
    last_logfile_number = 20
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 18, 2010"
    first_logfile_number = 1
    last_logfile_number = 20
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 19, 2010"
    first_logfile_number = 1
    last_logfile_number = 38
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 20, 2010"
    first_logfile_number = 72
    last_logfile_number = 139
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 25, 2010"
    first_logfile_number =1 
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 26, 2010"
    first_logfile_number = 1
    last_logfile_number = 80
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 28, 2010"
    first_logfile_number = 85
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/July 31, 2010"
    first_logfile_number = 1
    last_logfile_number = 65
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 01, 2010"
    first_logfile_number = 10
    last_logfile_number = 53
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 04, 2010"
    first_logfile_number = 100
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 05, 2010"
    first_logfile_number = 28
    last_logfile_number = 68
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 07, 2010"
    first_logfile_number = 1
    last_logfile_number = 63
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 11, 2010"
    first_logfile_number = 80
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 12, 2010"
    first_logfile_number = 40
    last_logfile_number = 1000


    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 16, 2010"
    first_logfile_number = 1
    last_logfile_number = 34
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 22, 2010"
    first_logfile_number = 60
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 23, 2010"
    first_logfile_number = 67
    last_logfile_number = 90
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 24, 2010"
    first_logfile_number = 1
    last_logfile_number = 40
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 25, 2010"
    first_logfile_number = 70
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 26, 2010"
    first_logfile_number = 20
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 27, 2010"
    first_logfile_number = 51
    last_logfile_number = 70
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/August 28, 2010"
    first_logfile_number = 40
    last_logfile_number = 80
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 01, 2010"
    first_logfile_number = 13
    last_logfile_number = 50
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 04, 2010"
    first_logfile_number = 10
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 07, 2010"
    first_logfile_number = 10
    last_logfile_number = 57
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 11, 2010"
    first_logfile_number =30 
    last_logfile_number = 48
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 12, 2010"
    first_logfile_number = 36
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 20, 2010"
    first_logfile_number = 16
    last_logfile_number = 27
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 26, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 29, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/September 30, 2010"
    first_logfile_number = 14
    last_logfile_number = 37
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/October 02, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/October 04, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/October 05, 2010"
    first_logfile_number = 16
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2010/October 06, 2010"
    first_logfile_number = 1
    last_logfile_number = 1000
    
