# Note that it's important to define input and output before image definition
# input = "H:/Raw Data/Summer 2016/February 19, 2016"
# input = "H:/Raw Data/Summer 2016/May 29, 2016"
input = "H:/Raw Data/Summer 2016/August 22, 2016"

output = "E:/Data Processing/Master Flats/2016"


[image]
rows = 1024
columns = 1024

