[image]
rows = 1024
columns = 1024


[processing]
no_of_images_to_combine = 10
radii_of_extraction = [3, 4, 5,]


[input]
### Flat usage is based on Wilkerson's Data Analysis Log Book pages 40-46
### Using 2-11 flat: 2-11 -> 2-24 and data acquistion logbook. See the digitalized
### version at: https://docs.google.com/spreadsheets/d/131Ol2Ud5NVF9tpf8rEcsMD6cwELk_w6d93A-M8KHinQ/edit#gid=1907236370

[[input.nights]]
path = "H://Raw Data/Summer 2012/February 11, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-02-11_masterflat_7.0.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/February 15, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-02-11_masterflat_7.0.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/February 17, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-02-11_masterflat_7.0.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/February 18, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-02-11_masterflat_7.0.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/February 21, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-02-11_masterflat_7.0.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/February 24, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-02-11_masterflat_7.0.fit"

# Camera installed 4-4
# ### Using 4-9 flat: 4-5 -> 4-30

[[input.nights]]
path = "H://Raw Data/Summer 2012/April 5, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-04-09_masterflat_7.0.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/April 7, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-04-09_masterflat_7.0.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/April 8, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-04-09_masterflat_7.0.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/April 9, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-04-09_masterflat_7.0.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/April 16, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-04-09_masterflat_7.0.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/April 22, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-04-09_masterflat_7.0.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/April 30, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-04-09_masterflat_7.0.fit"

# Camera rotated
### Using 5-10 flat: 5-9 -> 5-21

[[input.nights]]
path = "H://Raw Data/Summer 2012/May 9, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-05-10_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/May 10, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-05-10_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/May 12, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-05-10_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/May 13, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-05-10_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/May 14, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-05-10_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/May 15, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-05-10_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/May 16, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-05-10_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/May 17, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-05-10_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/May 18, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-05-10_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/May 20, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-05-10_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/May 21, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-05-10_masterflat.fit"


# Mirror lock tightened
### Using 6-11 flat: 5-24 -> 6-27

[[input.nights]]
path = "H://Raw Data/Summer 2012/May 24, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-05-10_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/May 28, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-05-10_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/June 9, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-05-10_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/June 11, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-06-11_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/June 16, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-06-11_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/June 19, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-06-11_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/June 21, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-06-11_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/June 24, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-06-11_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/June 25, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-06-11_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/June 26, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-06-11_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/June 27, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-06-11_masterflat.fit"

# Camera rotated
### Using 7-8 flat: 7-8, 7-9

[[input.nights]]
path = "H://Raw Data/Summer 2012/July 8, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-08_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/July 9, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-08_masterflat.fit"

# New telescope installed. That's what logbook says. But we (including Wilkerson)
# couldn't decipher what "new telescope" meant in this case. Because the new new
# telescope was supposed to be installed around end of 2011
### Using 7-14 flat: 7-11 ->  

[[input.nights]]
path = "H://Raw Data/Summer 2012/July 11, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/July 14, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/July 16, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/July 19, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/July 27, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/July 31, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"

[[input.nights]]
path = "H://Raw Data/Summer 2012/August 5, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
    
[[input.nights]]
path = "H://Raw Data/Summer 2012/August 7, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
    
[[input.nights]]
path = "H://Raw Data/Summer 2012/August 9, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
    
[[input.nights]]
path = "H://Raw Data/Summer 2012/August 10, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
    
[[input.nights]]
path = "H://Raw Data/Summer 2012/August 16, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
    
[[input.nights]]
path = "H://Raw Data/Summer 2012/August 17, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
    
[[input.nights]]
path = "H://Raw Data/Summer 2012/August 19, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
    
[[input.nights]]
path = "H://Raw Data/Summer 2012/August 20, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
    
[[input.nights]]
path = "H://Raw Data/Summer 2012/August 24, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
    
[[input.nights]]
path = "H://Raw Data/Summer 2012/August 29, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
    
[[input.nights]]
path = "H://Raw Data/Summer 2012/August 30, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
    
[[input.nights]]
path = "H://Raw Data/Summer 2012/September 5, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
        
[[input.nights]]
path = "H://Raw Data/Summer 2012/September 7, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
        
[[input.nights]]
path = "H://Raw Data/Summer 2012/September 9, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
        
[[input.nights]]
path = "H://Raw Data/Summer 2012/September 18, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
        
[[input.nights]]
path = "H://Raw Data/Summer 2012/September 19, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
        
[[input.nights]]
path = "H://Raw Data/Summer 2012/September 24, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
        
[[input.nights]]
path = "H://Raw Data/Summer 2012/September 26, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
        
[[input.nights]]
path = "H://Raw Data/Summer 2012/September 27, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
        
[[input.nights]]
path = "H://Raw Data/Summer 2012/September 29, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
    
[[input.nights]]
path = "H://Raw Data/Summer 2012/October 2, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"
        
[[input.nights]]
path = "H://Raw Data/Summer 2012/October 3, 2012"
masterflat = "E:/Data Processing/Master Flats/2012/2012-07-14_masterflat.fit"


[output]
path = "E:/Data Processing/Python Processed/2012"