# Note that it's important to define input and output before image definition
# input = "F:/Summer 2011/March 5, 2011"
# input = "F:/Summer 2011/May 26, 2011"
# input = "F:/Summer 2011/May 31, 2011"
input = "F:/Summer 2011/July 24, 2011"

output = "E:/Data Processing/Master Flats/2011"


[image]
rows = 1024
columns = 1024

