[processing]
radii_of_extraction = [3, 4, 5,]


[input]

    [[input.nights]]
    path = "E://Data Processing/Python Processed/2011/February 28, 2011"
    first_logfile_number = 1
    last_logfile_number = 1000

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/March 01, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/March 05, 2011"
    # first_logfile_number = 22
    # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/March 14, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 23

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/March 15, 2011"
    # first_logfile_number = 9
    # last_logfile_number = 1000    

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/March 18, 2011"
    # first_logfile_number = 6
    # last_logfile_number = 43
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/March 26, 2011"
    # first_logfile_number = 4
    # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/March 27, 2011"
    # first_logfile_number = 15
    # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/March 29, 2011"
    # first_logfile_number = 5
    # last_logfile_number = 25

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/April 01, 2011"
    # first_logfile_number = 10
    # last_logfile_number = 48

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/April 04, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 22

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/April 11, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 40
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/April 28, 2011"
    # first_logfile_number = 30
    # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/May 01, 2011"
    # first_logfile_number = 4
    # last_logfile_number = 70

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/May 03, 2011"
    # first_logfile_number = 9
    # last_logfile_number = 62   
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/May 15, 2011"
    # first_logfile_number = 5
    # last_logfile_number = 1000   

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/May 16, 2011"
    # first_logfile_number = 35
    # last_logfile_number = 1000   

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/May 26, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 40

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/May 31, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 34
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/June 11, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 40
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/June 27, 2011"
    # first_logfile_number = 10
    # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/June 28, 2011"
    # first_logfile_number = 20
    # last_logfile_number = 1000
    
    # # [[input.nights]]
    # # path = "E://Data Processing/Python Processed/2011/June 29, 2011"
    # # first_logfile_number = 1
    # # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/July 02, 2011"
    # first_logfile_number = 15
    # last_logfile_number = 43
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/July 04, 2011"
    # first_logfile_number = 6
    # last_logfile_number = 73    
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/July 08, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 75

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/July 20, 2011"
    # first_logfile_number = 15
    # last_logfile_number = 53
     
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/July 24, 2011"
    # first_logfile_number = 55
    # last_logfile_number = 68
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/July 29, 2011"
    # first_logfile_number = 13
    # last_logfile_number = 1000

    # # [[input.nights]]
    # # path = "E://Data Processing/Python Processed/2011/July 30, 2011"
    # # first_logfile_number = 1
    # # last_logfile_number = 1000
    
    # # [[input.nights]] Too few images
    # # path = "E://Data Processing/Python Processed/2011/August 06, 2011"
    # # first_logfile_number = 1
    # # last_logfile_number = 8
    
    # # [[input.nights]]
    # # path = "E://Data Processing/Python Processed/2011/August 07, 2011"
    # # first_logfile_number = 1
    # # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/August 11, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 17

    # # [[input.nights]]
    # # path = "E://Data Processing/Python Processed/2011/August 13, 2011"
    # # first_logfile_number = 1
    # # last_logfile_number = 1000
    
    # # [[input.nights]]
    # # path = "E://Data Processing/Python Processed/2011/August 17, 2011"
    # # first_logfile_number = 1
    # # last_logfile_number = 1000

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/August 21, 2011"
    # first_logfile_number = 21
    # last_logfile_number = 1000

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/August 24, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 44
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/August 25, 2011"
    # first_logfile_number = 19
    # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/August 31, 2011"
    # first_logfile_number = 4
    # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/August 26, 2011"
    # first_logfile_number = 3
    # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/September 01, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 36

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/September 07, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 30

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/September 08, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 20

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/September 09, 2011"
    # first_logfile_number = 13
    # last_logfile_number = 1000
    
    # # [[input.nights]]
    # # path = "E://Data Processing/Python Processed/2011/September 10, 2011"
    # # first_logfile_number = 1
    # # last_logfile_number = 1000
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/September 12, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 28
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/September 11, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 24
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/September 13, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 8

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/September 30, 2011"
    # first_logfile_number = 2
    # last_logfile_number = 11
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/October 01, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 19
    
    # # [[input.nights]]
    # # path = "E://Data Processing/Python Processed/2011/October 02, 2011"
    # # first_logfile_number = 1
    # # last_logfile_number = 1000
    
    # # [[input.nights]]
    # # path = "E://Data Processing/Python Processed/2011/October 03, 2011"
    # # first_logfile_number = 1
    # # last_logfile_number = 1000
    
    # # [[input.nights]]
    # # path = "E://Data Processing/Python Processed/2011/October 04, 2011"
    # # first_logfile_number = 1
    # # last_logfile_number = 1000
    
    # # [[input.nights]]
    # # path = "E://Data Processing/Python Processed/2011/October 05, 2011"
    # # first_logfile_number = 1
    # # last_logfile_number = 1000

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/October 07, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 16

    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/October 08, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 10
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/October 09, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 15
    
    # [[input.nights]]
    # path = "E://Data Processing/Python Processed/2011/October 11, 2011"
    # first_logfile_number = 1
    # last_logfile_number = 1000
    

   