# Note that it's important to define input and output before image definition
input = "F:/Summer 2021/September 1, 2021"
output = "E:/Data Processing/Master Flats/2021"


[image]
rows = 1024
columns = 1024

