[image]
rows = 1024
columns = 1024
crop_region = []

[processing]
no_of_images_to_combine = 20
radii_of_extraction = [ 3, 4, 5,]
cpu_fraction = 0.6
image_duration = 3.5
dark_prefix = "dark_"

[input]

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/February 22, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-02-22_masterflat_3.5.fit"
    
    
    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/February 23, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-02-22_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/March 3, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-02-22_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/March 5, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-02-22_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/March 7, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-03-07_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/March 9, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-03-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/March 10, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-03-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/March 12, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-03-12_masterflat_3.5.fit"
    
    # Only calibration taken on this date
    # [[input.nights]]
    # path = "G:/Raw Data/Summer 2008/March 19, 2008"
    # masterflat = "E:/Data Processing/Master Flats/2008/2008-03-19_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/March 25, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-03-19_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/April 1, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-03-19_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/April 4, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-04-04_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/April 13, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-04-04_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/April 14, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-04-04_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/April 15, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-04-04_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/April 22, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-04-04_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/April 29, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-04-04_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/May 3, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-04-04_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/May 4, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-04-04_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/May 5, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-04-04_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/May 9, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-04-04_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/May 11, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-04-04_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/May 15, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-04-04_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/May 17, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-04-04_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/May 20, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-04-04_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/May 23, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-04-04_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/May 30, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-04-04_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/June 6, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-06-06_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/June 15, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-06-06_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/June 16, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-06-06_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/June 22, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-06-06_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/June 29, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-06-06_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/June 30, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-06-06_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/July 2, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-06-06_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/July 4, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-06-06_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/July 5, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-06-06_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/July 8, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-06-06_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/July 9, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-06-06_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/July 12, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/July 13, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/July 21, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/July 22, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/July 25, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/July 26, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/July 30, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/August 1, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/August 5, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/August 6, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/August 7, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/August 9, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/August 15, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/August 17, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/August 18, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/August 19, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/August 23, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/August 24, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/August 25, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/August 26, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    
    # Cant find darks
    # [[input.nights]]
    # path = "G:/Raw Data/Summer 2008/August 29, 2008"
    # masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/August 30, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/August 31, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/September 15, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/September 16, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/September 17, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/September 18, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2008/September 21, 2008"
    masterflat = "E:/Data Processing/Master Flats/2008/2008-07-12_masterflat_3.5.fit"
    


[output]
path = "E:/Data Processing/Python Processed/2008"