# Note that it's important to define input and output before image definition
# input = "H:/Raw Data/Summer 2013/March 1, 2013"
input = "H:/Raw Data/Summer 2013/June 27, 2013"
output = "E:/Data Processing/Master Flats/2013"


[image]
rows = 1024
columns = 1024

