[image]
rows = 1024
columns = 1024


[processing]
no_of_images_to_combine = 10
radii_of_extraction = [3, 4, 5,]


[input]
# Using 3-1 flat: 3-1 -> 6-18
    [[input.nights]]
    path = "H://Raw Data/Summer 2013/March 1, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/March 12, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/March 19, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/March 20, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/March 27, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/March 28, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/April 2, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/April 3, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/April 19, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/April 23, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/May 7, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/May 11, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/May 12, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/May 13, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/May 14, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/May 23, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/June 10, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/June 13, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/June 18, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-03-01_masterflat.fit"

# Using 6-27 flat: 6-27 -> 
    [[input.nights]]
    path = "H://Raw Data/Summer 2013/June 27, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/July 4, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/July 9, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/July 10, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/July 11, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/July 14, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/July 16, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/July 17, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/July 23, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/July 28, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/July 31, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/August 3, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/August 12, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/August 13, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/August 22, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/August 25, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/August 27, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/August 29, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/September 1, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/September 5, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/September 12, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/September 16, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/September 18, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/September 22, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/September 23, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/September 25, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/September 26, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/September 29, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"

    [[input.nights]]
    path = "H://Raw Data/Summer 2013/October 1, 2013"
    masterflat = "E:/Data Processing/Master Flats/2013/2013-06-27_masterflat.fit"
    
[output]
path = "E:/Data Processing/Python Processed/2013"