[image]
rows = 1024
columns = 1024
crop_region = []

[processing]
no_of_images_to_combine = 25
radii_of_extraction = [ 3, 4, 5,]
cpu_fraction = 0.6
image_duration = 2.8
dark_prefix = "dark_"

[input]
[[input.nights]]
path = "F:/Summer 2007/March 9, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-03-05_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/March 10, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-03-05_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/March 19, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-03-17_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/March 22, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-03-17_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/March 25, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-03-17_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/April 4, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-03-17_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/April 5, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-03-17_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/April 8, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-03-17_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/April 14, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-03-17_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/April 15, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-03-17_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/April 16, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-03-17_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/April 17, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-03-17_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/April 20, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-04-20_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/April 21, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-04-21_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/April 27, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-04-21_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/April 28, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-04-21_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/May 2, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-04-21_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/May 8, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-04-21_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/May 9, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-04-21_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/May 10, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-04-21_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/May 11, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-04-21_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/May 13, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-04-21_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/May 15, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-04-21_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/May 16, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-04-21_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/May 17, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-04-21_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/May 18, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-05-18_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/May 21, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-05-18_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/June 5, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-05-18_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/June 8, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-05-18_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/June 18, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-05-18_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/June 19, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-06-19_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/June 23, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-06-19_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/June 25, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-06-19_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/July 1, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-06-19_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/July 5, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-06-19_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/July 6, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-06-19_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/July 10, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-06-19_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/July 15, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-06-19_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/July 19, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-06-19_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/July 20, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-20_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/July 21, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-20_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/July 24, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-20_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/July 29, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-29_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/July 30, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-29_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/July 31, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-29_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/August 2, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-29_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/August 9, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-29_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/August 16, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-29_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/August 25, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-29_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/August 26, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-29_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/August 27, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-29_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/August 29, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-29_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/August 30, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-29_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/August 31, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-29_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/September 1, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-29_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/September 2, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-29_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/September 3, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-29_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/September 4, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-07-29_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/September 11, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-09-11_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/September 12, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-09-12_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/September 14, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-09-12_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/September 16, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-09-12_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/September 27, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-09-12_masterflat_2.8.fit"

[[input.nights]]
path = "F:/Summer 2007/October 3, 2007"
masterflat = "E:/Data Processing/Master Flats/2007/2007-09-12_masterflat_2.8.fit"

[output]
path = "E:/Data Processing/Python Processed/2007"