[processing]
radii_of_extraction = [3, 4, 5,]
cpu_fraction = 0.6

[input]

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/March 09, 2007"
    first_logfile_number = 35
    last_logfile_number = 52
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/March 10, 2007"
    first_logfile_number = 31
    last_logfile_number = 50
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/March 19, 2007"
    first_logfile_number = 18
    last_logfile_number = 51
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/March 22, 2007"
    first_logfile_number = 45
    last_logfile_number = 70
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/March 25, 2007"
    first_logfile_number = 14
    last_logfile_number = 71
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/April 04, 2007"
    first_logfile_number = 12
    last_logfile_number = 55
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/April 05, 2007"
    first_logfile_number = 18
    last_logfile_number = 38
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/April 14, 2007"
    first_logfile_number = 20
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/April 16, 2007"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/April 20, 2007"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/April 21, 2007"
    first_logfile_number = 60
    last_logfile_number = 77
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/April 27, 2007"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/May 02, 2007"
    first_logfile_number = 1
    last_logfile_number = 80
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/May 09, 2007"
    first_logfile_number = 25
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/May 10, 2007"
    first_logfile_number = 27
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/May 11, 2007"
    first_logfile_number = 21
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/May 13, 2007"
    first_logfile_number = 21
    last_logfile_number = 76
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/May 15, 2007"
    first_logfile_number = 20
    last_logfile_number = 80
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/May 16, 2007"
    first_logfile_number = 21
    last_logfile_number = 115
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/May 17, 2007"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/May 18, 2007"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/May 21, 2007"
    first_logfile_number = 40
    last_logfile_number = 120
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/June 05, 2007"
    first_logfile_number = 11
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/June 08, 2007"
    first_logfile_number = 1
    last_logfile_number = 135
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/June 18, 2007"
    first_logfile_number = 65
    last_logfile_number = 120
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/June 19, 2007"
    first_logfile_number = 20
    last_logfile_number = 140
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/June 23, 2007"
    first_logfile_number = 10
    last_logfile_number = 70
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/June 25, 2007"
    first_logfile_number = 1
    last_logfile_number = 80
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/July 01, 2007"
    first_logfile_number = 1
    last_logfile_number = 23
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/July 05, 2007"
    first_logfile_number = 1
    last_logfile_number = 110
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/July 06, 2007"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/July 10, 2007"
    first_logfile_number = 18
    last_logfile_number = 120
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/July 15, 2007"
    first_logfile_number = 7
    last_logfile_number = 55
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/July 19, 2007"
    first_logfile_number = 6
    last_logfile_number = 100
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/July 20, 2007"
    first_logfile_number = 1
    last_logfile_number = 14
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/July 21, 2007"
    first_logfile_number = 12
    last_logfile_number = 30
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/July 24, 2007"
    first_logfile_number = 1
    last_logfile_number = 80
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/July 29, 2007"
    first_logfile_number = 1
    last_logfile_number = 80
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/July 30, 2007"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/July 31, 2007"
    first_logfile_number = 60
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/August 02, 2007"
    first_logfile_number = 5
    last_logfile_number = 67
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/August 09, 2007"
    first_logfile_number = 1
    last_logfile_number = 66
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/August 16, 2007"
    first_logfile_number = 1
    last_logfile_number = 61
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/August 25, 2007"
    first_logfile_number = 20
    last_logfile_number = 67
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/August 26, 2007"
    first_logfile_number = 30
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/August 27, 2007"
    first_logfile_number = 1
    last_logfile_number = 59
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/August 29, 2007"
    first_logfile_number = 4
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/August 30, 2007"
    first_logfile_number = 1
    last_logfile_number = 53
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/August 31, 2007"
    first_logfile_number = 1
    last_logfile_number = 51
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/September 01, 2007"
    first_logfile_number = 5
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/September 02, 2007"
    first_logfile_number = 19
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/September 03, 2007"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/September 04, 2007"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/September 11, 2007"
    first_logfile_number = 9
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/September 12, 2007"
    first_logfile_number = 6
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/September 14, 2007"
    first_logfile_number = 7
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/September 16, 2007"
    first_logfile_number = 7
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/September 27, 2007"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2007/October 03, 2007"
    first_logfile_number = 6
    last_logfile_number = 1000
    
