[image]
rows = 1024
columns = 1024


[processing]
no_of_images_to_combine = 20
radii_of_extraction = [3, 4, 5,]
image_duration = 3.5
cpu_fraction = 0


[input]

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/June 18, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/June 19, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/June 20, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/June 28, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/June 29, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/June 30, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/July 1, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/July 2, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/July 15, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/July 18, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/July 22, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/July 23, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/July 24, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/July 30, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/August 3, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/August 4, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/August 11, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/August 12, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/August 15, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/August 21, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/2003-06-23_masterflat_3.5.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/August 23, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/masterflat_09-11-03.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/August 26, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/masterflat_09-11-03.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/August 29, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/masterflat_09-11-03.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/September 1, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/masterflat_09-11-03.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/September 2, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/masterflat_09-11-03.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/September 3, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/masterflat_09-11-03.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/September 5, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/masterflat_09-11-03.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/September 6, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/masterflat_09-11-03.fit"
    

    [[input.nights]]
    path = "G:/Raw Data/Summer 2003/September 7, 2003"
    masterflat = "E:/Data Processing/Master Flats/2003/masterflat_09-11-03.fit"
    

    # [[input.nights]]
    # path = "G:/Raw Data/Summer 2003/September 8, 2003"
    # masterflat = "E:/Data Processing/Master Flats/2003/masterflat_09-11-03.fit"
    

    

[output]
path = "E:/Data Processing/Python Processed/2003"
save_aligned = true
save_calibrated = true