[processing]
radii_of_extraction = [3, 4, 5,]


[input]
    
    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/June 18, 2003"
    first_logfile_number = 78
    last_logfile_number = 127
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/June 19, 2003"
    first_logfile_number = 1
    last_logfile_number = 138
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/June 20, 2003"
    first_logfile_number = 1
    last_logfile_number = 145
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/June 28, 2003"
    first_logfile_number = 30
    last_logfile_number = 49
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/June 29, 2003"
    first_logfile_number = 1
    last_logfile_number = 32
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/June 30, 2003"
    first_logfile_number = 96
    last_logfile_number = 146
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/July 01, 2003"
    first_logfile_number = 45
    last_logfile_number = 130
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/July 02, 2003"
    first_logfile_number = 3
    last_logfile_number = 65
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/July 15, 2003"
    first_logfile_number = 19
    last_logfile_number = 82
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/July 18, 2003"
    first_logfile_number = 12
    last_logfile_number = 122
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/July 22, 2003"
    first_logfile_number = 9
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/July 23, 2003"
    first_logfile_number = 1
    last_logfile_number = 50
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/July 24, 2003"
    first_logfile_number = 1
    last_logfile_number = 74
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/July 30, 2003"
    first_logfile_number = 17
    last_logfile_number = 98
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/August 03, 2003"
    first_logfile_number = 9
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/August 04, 2003"
    first_logfile_number = 9
    last_logfile_number = 79
    

    # [[input.nights]] no data
    # path = "E:/Data Processing/Python Processed/2003/August 11, 2003"
    # first_logfile_number = 
    # last_logfile_number = 
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/August 12, 2003"
    first_logfile_number = 1
    last_logfile_number = 43
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/August 15, 2003"
    first_logfile_number = 51
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/August 21, 2003"
    first_logfile_number = 10
    last_logfile_number = 48
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/August 23, 2003"
    first_logfile_number = 5
    last_logfile_number = 51
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/August 26, 2003"
    first_logfile_number = 1
    last_logfile_number = 42
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/August 29, 2003"
    first_logfile_number = 1
    last_logfile_number = 20
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/September 01, 2003"
    first_logfile_number = 1
    last_logfile_number = 55
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/September 02, 2003"
    first_logfile_number = 1
    last_logfile_number = 27
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/September 03, 2003"
    first_logfile_number = 1
    last_logfile_number = 26
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/September 05, 2003"
    first_logfile_number = 1
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/September 06, 2003"
    first_logfile_number = 5
    last_logfile_number = 1000
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/September 07, 2003"
    first_logfile_number = 5
    last_logfile_number = 54
    

    [[input.nights]]
    path = "E:/Data Processing/Python Processed/2003/September 08, 2003"
    first_logfile_number = 1
    last_logfile_number = 50
    
